// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzO5PRcX-LFvQwGVLO7PgKOFp-pa_NRfc',
    appId: '1:45233715486:web:e60f86808b8a49d9f2710f',
    messagingSenderId: '45233715486',
    projectId: 'healthcare-e4cc6',
    authDomain: 'healthcare-e4cc6.firebaseapp.com',
    storageBucket: 'healthcare-e4cc6.appspot.com',
    measurementId: 'G-FJ8QL6D1TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjoXqkXuzqSWgZaBTjOfoHd5z5RshmcO8',
    appId: '1:45233715486:android:c2d08184ee8d4251f2710f',
    messagingSenderId: '45233715486',
    projectId: 'healthcare-e4cc6',
    storageBucket: 'healthcare-e4cc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCucj5XMPyzzBD0zAzDULq1BWqDkLJ-Eyg',
    appId: '1:45233715486:ios:8867767e96a3aa89f2710f',
    messagingSenderId: '45233715486',
    projectId: 'healthcare-e4cc6',
    storageBucket: 'healthcare-e4cc6.appspot.com',
    iosBundleId: 'com.example.healthcareFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCucj5XMPyzzBD0zAzDULq1BWqDkLJ-Eyg',
    appId: '1:45233715486:ios:8867767e96a3aa89f2710f',
    messagingSenderId: '45233715486',
    projectId: 'healthcare-e4cc6',
    storageBucket: 'healthcare-e4cc6.appspot.com',
    iosBundleId: 'com.example.healthcareFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzO5PRcX-LFvQwGVLO7PgKOFp-pa_NRfc',
    appId: '1:45233715486:web:dccc5675dfd1666ff2710f',
    messagingSenderId: '45233715486',
    projectId: 'healthcare-e4cc6',
    authDomain: 'healthcare-e4cc6.firebaseapp.com',
    storageBucket: 'healthcare-e4cc6.appspot.com',
    measurementId: 'G-GHH7JKVJ5H',
  );
}
